services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: login
    ports:
      - "3307:3306"        # Porta 3307 do host, 3306 do container
    volumes:
      - mysql_data:/var/lib/mysql

  nest-app:
    build: .
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mysql
volumes:
  mysql_data:
